

#配置数据库连接信息
spring:
  datasource:
    #下面这两个配置，可以在每次连接的时候判断一些连接是否有效
    druid.test-on-borrow: true
    druid.test-while-idle: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chuizi?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true


#mapper映射
mybatis:  #mybatyis的配置
  type-aliases-package: com.chuizi.entiy
  mapper-locations: classpath:mapper/*Mapper.xml #指定mapper的配置文件的路径是mapper文件夹下的所有 xml文件。
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.gooann.Mapper: debug
server:
  port: 8090